image: "node:carbon"

services:
  - mongo:latest

cache:
  paths:
  - node_modules/

variables:
  MONGO_TEST_URL: "mongodb://mongo/test_database"
  NODE_ENV: "test"
  SECRET: "secret"

test:
  script:
  - npm install
  - npm test

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-nodejs-test-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-nodejs-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags
